#code from lectures and GAE documentation
application: reuse-group17
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: main.application
  login: required
  
libraries: 
- name: webapp2
  version: latest 
- name: jinja2
  version: latest